#include "keyboard_fn.h"

#define ACTION_RADIAL_PRESS ACTION_FUNCTION_OPT(RADIAL_CONTROLL, 0)
#define ACTION_RADIAL_CLOCKWISE ACTION_FUNCTION_OPT(RADIAL_CONTROLL, 1)
#define ACTION_RADIAL_ANTICLOCKWISE ACTION_FUNCTION_OPT(RADIAL_CONTROLL, 0x0F)
